### PR TITLE
Runtime

### PR DESCRIPTION
**Pull request by stebranchi**
I'm recreating the pull request because I assume that the reset deleted the previous one

### CODE REVIEW

**Comment by TKasekamp** [comment]
Your problem is that you are working in a version that is behind the current master branch. You have to do git pull before starting adding new code and creating a new branch. 
Right now you are also commiting things that are already in the repository.

**Comment by TKasekamp** [comment]
You used git reset on a pull requst that was too far behind. The most recent one that you have to build upon is 3ee2e7dc944dbaf2c7c7d20cdae13fbfe55dbe5a

**Comment by TKasekamp** [comment]
Are all your changes working and final? if so i'll do some git magic.

**Comment by stebranchi** [comment]
You told me to take the last pull request that was the #48. By the way I added all my code so now should be equal to my last version with the xgboost in the core/folder. Now I solve the last errors and should be fine

**Comment by TKasekamp** [comment]
Sorry i just used the version number and assumed #48 was the most recent. But the latest commit to master was actually https://github.com/nirdizati-research/predict-python/commit/3ee2e7dc944dbaf2c7c7d20cdae13fbfe55dbe5a

**Comment by stebranchi** [comment]
Ah ok, sorry for that. By the way I think I could say this is a final
version for the tomorrow call, after that i will add semaphore for database
accesses from different threads. Do all the magic you want

Il giorno mer 13 giu 2018 alle ore 14:17 Tõnis Kasekamp <
notifications@github.com> ha scritto:

**Comment by TKasekamp** [comment]
Nope this is all. Basically what i did was `git reset 3ee2e7dc944dbaf2c7c7d20cdae13fbfe55dbe5a`, added only your things to commit and then `git push -f`. 

Semaphores are a bit big. Are you really sure you need them? And not just fixing a thing that might need a bigger re-design?

**Comment by stebranchi** [comment]
Ok. For semaphores I don't know, we will talk tomorrow about that

Il Mer 13 Giu 2018, 15:40 Tõnis Kasekamp <notifications@github.com> ha
scritto:

**Pull request merged**
